---
title: "Sonde Analysis"
author: "Rhegan Thomason"
date: '2022-06-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=FALSE}
library(tidyverse)
sn811761 <- read.csv("sn811761.csv", skip=25)
sn461132 <- read.csv("sn461132.csv", skip=25)
sn788735 <- read.csv("sn788735.csv", skip=25)
sn811737 <- read.csv("sn811737.csv", skip=25)
sn461051 <- read.csv("sn461051.csv", skip=25)
```

## pH

Here it issssss

```{r pH, echo=FALSE}
thesenames <- c ("Date Time", "Actual Conductivity (µS/cm)", "Specific Conductivity (µS/cm)", "Salinity (PSU)", "Resistivity (Ω⋅cm)", "Density (g/cm³)", "Total Dissolved Solids (ppt)", "Chlorophyll-a Fluorescence (RFU)", "RDO Concentration (mg/L)", "RDO Saturation (%Sat)", "Oxygen Partial Pressure (Torr)", "pH", "pH mV", "ORP (mV)", "Temperature (°C)", "External Voltage (V)", "Battery Capacity (%)", "Barometric Pressure (mm Hg)", "Pressure (psi)", "Depth (m)", "new_col")
sn461051$new_col <- "461051"
sn461132$new_col <- "461132"
sn811761$new_col <- "811761"
sn811737$new_col <- "811737"
sn788735$new_col <- "788735"
names(sn461051) = thesenames
names(sn461132) = thesenames
names(sn811737) = thesenames
names(sn811761) = thesenames
names(sn788735) = thesenames
fulldata <- bind_rows(sn811737, sn461051, sn811761, sn461132, sn788735)
ggplot(data = fulldata, aes(`Date Time`, `pH`, group=new_col))+ geom_line(aes(color=new_col))+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```
